name = "blog"
type = "webpack"
account_id = "cc758ee73b4ad18422df688289ec3b21"
workers_dev = false
route = "devinschulz.com/*"
zone_id = "383edf4ae939a2fa006deb8e6b1a2ebd"

[site]
bucket = "public"
entry-point = "workers-site"
